field: 8bf74dca-3e01-4f16-839f-ab05cf7f48be
fieldLayouts:
  a71e3b97-9400-4dcd-8a60-a6f6908088a5:
    tabs:
      -
        fields:
          098956d1-c77e-44bc-9d05-550d145f5b5b:
            required: false
            sortOrder: 2
          c290dc09-5ee4-4660-9c97-369996e62430:
            required: false
            sortOrder: 1
          f71db32b-985f-4787-b4b6-3f8ffb160908:
            required: false
            sortOrder: 3
        name: Content
        sortOrder: 1
fields:
  098956d1-c77e-44bc-9d05-550d145f5b5b:
    contentColumnType: string
    fieldGroup: null
    handle: contenuto
    instructions: ''
    name: Contenuto
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: '1'
      columnType: text
      configFile: Simple.json
      purifierConfig: ''
      purifyHtml: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  c290dc09-5ee4-4660-9c97-369996e62430:
    contentColumnType: text
    fieldGroup: null
    handle: titolo
    instructions: ''
    name: Titolo
    searchable: true
    settings:
      charLimit: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f71db32b-985f-4787-b4b6-3f8ffb160908:
    contentColumnType: text
    fieldGroup: null
    handle: idBlocco
    instructions: "Id per url.\r\nNon usare # nel valore, esempio:\r\nvalore: \"test\"\r\nurl: dominio.com/pagina#test"
    name: 'Id blocco'
    searchable: true
    settings:
      charLimit: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: bloccoLibero
name: 'Blocco libero'
sortOrder: 5
