fieldLayouts:
  d0359088-d8c2-4a75-8107-4b4c89ee58e4:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Titolo
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: b7d83b30-ca1a-463e-adb9-8b9fae1169fc
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: cdd19e48-58f4-4712-95b9-fc58e8a679b5
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 671f7cc9-2dca-48e4-820f-7bb5986023be
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: d5ae378d-b90d-4736-89a1-840cf0eab13e
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Blocco tab'
        sortOrder: 1
handle: blocchiTab
hasTitleField: true
name: 'Blocchi tab'
section: aae40d0c-273b-45c6-a072-062a51303542
sortOrder: 1
titleFormat: null
