fieldLayouts:
  278a7212-dd8d-4c30-bcea-c9a75768e143:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Titolo
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: fce263b4-c698-4d79-9071-76521b937000
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 59575f03-bfd4-48da-8f42-251d29c4382e
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: eba89519-e384-43bb-8a62-94d21a24c1dd
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 23a0f0ce-5a47-47ba-8e95-2a08c5de4917
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 59b60c63-d0bf-4274-9421-b38c038ba954
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: GENERALI
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 8bf74dca-3e01-4f16-839f-ab05cf7f48be
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: CONTENUTO
        sortOrder: 2
      -
        elements:
          -
            fieldUid: d5ae378d-b90d-4736-89a1-840cf0eab13e
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 671f7cc9-2dca-48e4-820f-7bb5986023be
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: cdd19e48-58f4-4712-95b9-fc58e8a679b5
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: b7d83b30-ca1a-463e-adb9-8b9fae1169fc
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Blocco tab'
        sortOrder: 3
      -
        elements:
          -
            fieldUid: a7cbdef6-e7fb-4670-9d70-c5a368061121
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 849050c3-4fe8-468e-ab77-1cd2633cba3b
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Blocco carousel'
        sortOrder: 4
      -
        elements:
          -
            fieldUid: d1940035-3723-4406-b107-0c59c8f03c08
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'CASI DI SUCCESSO'
        sortOrder: 5
      -
        elements:
          -
            fieldUid: 8caedc5d-ad29-4e2a-ab8f-1e13f219501e
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Campi seo'
        sortOrder: 6
handle: soluzioni
hasTitleField: true
name: Soluzioni
section: d41b714e-e17f-4ea2-b55f-f3b9228eca80
sortOrder: 1
titleFormat: null
