fieldLayouts:
  c2641c9d-6312-44e5-9aeb-6e538a92129c:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Contenuto
        sortOrder: 1
handle: userPhotos
hasUrls: false
name: 'User Photos'
settings:
  path: '@storage/userphotos'
sortOrder: 3
type: craft\volumes\Local
url: ''
