contentColumnType: string
fieldGroup: f81f7bf4-af67-403d-9134-a74a98559e15
handle: abstract
instructions: ''
name: Abstract
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  cleanupHtml: '1'
  columnType: text
  configFile: ''
  purifierConfig: ''
  purifyHtml: '1'
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
