contentColumnType: string
fieldGroup: f81f7bf4-af67-403d-9134-a74a98559e15
handle: body
instructions: null
name: Body
searchable: true
settings:
  columnType: text
  configFile: Standard.json
translationKeyFormat: null
translationMethod: site
type: craft\redactor\Field
