contentColumnType: text
fieldGroup: 5c7bd7f1-5563-4380-8339-b42023e3b36b
handle: contatti_comePossiamoAiutarti
instructions: ''
name: 'Come possiamo aiutarti?'
searchable: true
settings:
  charLimit: null
  columnType: text
  multiline: 1
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
