contentColumnType: text
fieldGroup: 6469850b-1d09-4388-8d8c-4a1a1c9ea2ba
handle: customOgDescription
instructions: ''
name: 'Custom og description'
searchable: true
settings:
  charLimit: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
