contentColumnType: string
fieldGroup: c5bfb4ba-a751-44a0-9094-2fdfed06ede3
handle: customSeoMeta
instructions: ''
name: 'Custom Seo Meta'
searchable: true
settings:
  assetSources:
    - 'folder:1'
  openGraphType: ''
  openGraphTypeChangeable: '1'
  robots: ''
  robotsChangeable: '1'
  seoDescription: ''
  seoDescriptionSource: custom
  seoDescriptionSourceChangeable: '1'
  seoDescriptionSourceField: title
  seoFacebookImageIdSource: custom
  seoFacebookImageIdSourceChangeable: '1'
  seoFacebookImageIdSourceField: customOgImage
  seoFacebookImageTransform: ''
  seoImageIdSource: custom
  seoImageIdSourceChangeable: '1'
  seoImageIdSourceField: customOgImage
  seoImageTransform: ''
  seoKeywords: ''
  seoKeywordsSource: custom
  seoKeywordsSourceChangeable: '1'
  seoKeywordsSourceField: title
  seoMainEntityCategory: CreativeWork
  seoMainEntityOfPage: WebPage
  seoTitle: ''
  seoTitleSource: field
  seoTitleSourceChangeable: '1'
  seoTitleSourceField: title
  seoTwitterImageIdSource: custom
  seoTwitterImageIdSourceChangeable: '1'
  seoTwitterImageIdSourceField: customOgImage
  seoTwitterImageTransform: ''
  twitterCardType: ''
  twitterCardTypeChangeable: '1'
translationKeyFormat: null
translationMethod: none
type: Seomatic_Meta
