contentColumnType: text
fieldGroup: 0ff95cd1-1e99-432e-ade8-27d1c222c95c
handle: dataEventoTesto
instructions: 'Mostrata in alto nell''evento singolo'
name: 'Data evento testo'
searchable: true
settings:
  charLimit: ''
  columnType: text
  initialRows: '4'
  multiline: '1'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
