contentColumnType: datetime
fieldGroup: 0ff95cd1-1e99-432e-ade8-27d1c222c95c
handle: dataEvento
instructions: 'Usata per ordinamento'
name: 'Data evento'
searchable: true
settings:
  minuteIncrement: '30'
  showDate: 1
  showTime: 0
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
