contentColumnType: text
fieldGroup: 4fb7ae08-4783-420e-bb59-19a70c9df682
handle: digitalBreakfastConMitech_ruoloAziendale
instructions: ''
name: 'Ruolo Aziendale'
searchable: true
settings:
  charLimit: null
  columnType: text
  multiline: 0
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
