contentColumnType: string
fieldGroup: 0ff95cd1-1e99-432e-ade8-27d1c222c95c
handle: documentiEvento
instructions: ''
name: Documenti
searchable: true
settings:
  contentTable: '{{%matrixcontent_documentievento}}'
  maxBlocks: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: none
type: craft\fields\Matrix
