contentColumnType: text
fieldGroup: c187e0e2-1954-48d5-bb83-08e2691733ce
handle: formLanding_azienda
instructions: ''
name: Azienda
searchable: true
settings:
  charLimit: null
  columnType: text
  multiline: 0
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
