contentColumnType: string
fieldGroup: 2eed2783-3562-4c4c-8bee-a2933c182cd4
handle: formContattiIcona
instructions: ''
name: 'Form contatti icona'
searchable: true
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:3ec8853a-a014-463e-848d-7da4f8a9bfac'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: ''
  singleUploadLocationSource: 'volume:3ec8853a-a014-463e-848d-7da4f8a9bfac'
  singleUploadLocationSubpath: ''
  sources: '*'
  useSingleFolder: ''
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
