contentColumnType: text
fieldGroup: ef05658d-df64-4789-a6b0-f454568fe368
handle: homeIntroTitolo
instructions: ''
name: Titolo
searchable: true
settings:
  charLimit: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
