contentColumnType: text
fieldGroup: 15964ac7-d0b9-40ef-b127-665260a7d52a
handle: htKickOffDay2019_cognome
instructions: ''
name: Cognome
searchable: true
settings:
  charLimit: null
  columnType: text
  multiline: 0
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
