contentColumnType: string
fieldGroup: f81f7bf4-af67-403d-9134-a74a98559e15
handle: immaginePrincipale
instructions: ''
name: 'Immagine principale'
searchable: true
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:3ec8853a-a014-463e-848d-7da4f8a9bfac'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: ''
  singleUploadLocationSource: 'volume:3ec8853a-a014-463e-848d-7da4f8a9bfac'
  singleUploadLocationSubpath: ''
  sources: '*'
  useSingleFolder: ''
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
