contentColumnType: text
fieldGroup: c7d04f2d-dae7-4f28-abd7-de0466646eb4
handle: landingNewsletterIntroduzione
instructions: ''
name: 'Landing newsletter introduzione'
searchable: true
settings:
  charLimit: ''
  columnType: text
  initialRows: '4'
  multiline: '1'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
