contentColumnType: text
fieldGroup: a6ad4146-aea7-4dc9-af27-04cf8ef80403
handle: lavoraConNoi_message
instructions: ''
name: Message
searchable: true
settings:
  charLimit: null
  columnType: text
  multiline: 1
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
