contentColumnType: integer(10)
fieldGroup: 2eed2783-3562-4c4c-8bee-a2933c182cd4
handle: modalNewsletterTimeout
instructions: "Dopo quanti secondi deve essere mostrata la modal (inserire un numero intero).\r\nLasciare a 0 per non mostrare la modal automaticamente."
name: 'Modal newsletter timeout'
searchable: true
settings:
  decimals: '0'
  max: ''
  min: '0'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
