contentColumnType: text
fieldGroup: 2eed2783-3562-4c4c-8bee-a2933c182cd4
handle: paragrafoMarkerMappa
instructions: ''
name: 'Paragrafo marker mappa'
searchable: true
settings:
  charLimit: ''
  columnType: text
  initialRows: '2'
  multiline: '1'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
