contentColumnType: string
fieldGroup: 0ff95cd1-1e99-432e-ade8-27d1c222c95c
handle: programmaEventoIntroduzione
instructions: ''
name: 'Introduzione Programma'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  cleanupHtml: '1'
  columnType: text
  configFile: ''
  purifierConfig: ''
  purifyHtml: '1'
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
