contentColumnType: text
fieldGroup: f81f7bf4-af67-403d-9134-a74a98559e15
handle: sottotitolo
instructions: ''
name: Sottotitolo
searchable: true
settings:
  charLimit: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
