contentColumnType: string
fieldGroup: f81f7bf4-af67-403d-9134-a74a98559e15
handle: tags
instructions: null
name: Tags
searchable: true
settings:
  localizeRelations: false
  source: 'taggroup:82110da6-0a40-4f9e-b0b9-0aaeff7c70c9'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Tags
