enableVersioning: true
handle: homepage
name: Homepage
previewTargets:
  -
    label: 'Pagina articolo primaria'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  5923a219-cdcb-4ce4-842e-f6e77f429764:
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
  644656eb-2858-42a7-b937-c3c8abed971c:
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
