enableVersioning: true
handle: landing
name: Landing
previewTargets:
  -
    label: 'Pagina articolo primaria'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  5923a219-cdcb-4ce4-842e-f6e77f429764:
    enabledByDefault: true
    hasUrls: true
    template: cmpg/_entry
    uriFormat: '{% if object.level == 1 %}cmpg/{slug}{% else %}{parent.uri}/{slug}{% endif %}'
  644656eb-2858-42a7-b937-c3c8abed971c:
    enabledByDefault: true
    hasUrls: true
    template: cmpg/_entry
    uriFormat: '{% if object.level == 1 %}cmpg/{slug}{% else %}{parent.uri}/{slug}{% endif %}'
structure:
  maxLevels: null
  uid: 318efb1d-f914-464e-8455-1a96e11b59a6
type: structure
