enableVersioning: true
handle: pagine
name: Pagine
previewTargets:
  -
    label: 'Pagina articolo primaria'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  5923a219-cdcb-4ce4-842e-f6e77f429764:
    enabledByDefault: true
    hasUrls: true
    template: servizi/_entry
    uriFormat: '{% if object.level == 1 %}{slug}{% else %}{parent.uri}/{slug}{% endif %}'
  644656eb-2858-42a7-b937-c3c8abed971c:
    enabledByDefault: true
    hasUrls: true
    template: servizi/_entry
    uriFormat: '{% if object.level == 1 %}{slug}{% else %}{parent.uri}/{slug}{% endif %}'
structure:
  maxLevels: null
  uid: 896ca81c-268f-40ba-8de4-47417e3ab7cb
type: structure
