enableVersioning: true
handle: servizi
name: Servizi
previewTargets:
  -
    label: 'Pagina articolo primaria'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  5923a219-cdcb-4ce4-842e-f6e77f429764:
    enabledByDefault: true
    hasUrls: true
    template: servizi/_entry
    uriFormat: '{% if object.level == 1 %}servizi/{slug}{% else %}{parent.uri}/{slug}{% endif %}'
  644656eb-2858-42a7-b937-c3c8abed971c:
    enabledByDefault: true
    hasUrls: true
    template: servizi/_entry
    uriFormat: '{% if object.level == 1 %}servizi/{slug}{% else %}{parent.uri}/{slug}{% endif %}'
structure:
  maxLevels: 2
  uid: aa4088df-7941-465c-900d-608e3959cff5
type: structure
